apiVersion: v1
kind: Service
metadata:
  name: calc-service
  labels:
    app: calc-app
spec:
  type: LoadBalancer
  selector:
    app: calc-app
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 6000